### ISSUE TITLE
Is this cookbook listed on Supermarket?

### ISSUE THREAD

**Issue by davidpellerin** [ballistiq/chef-passenger-nginx#8]
@leonardteo Just wondering if this cookbook is listed on [supermarket.chef.io](supermarket.chef.io) ?

**Comment by leonardteo** [comment]
@davidpellerin no, the script was really built for my own individual purposes because the official ones didn't support things like building nginx and passenger enterprise. Unfortunately I'm not intending on supporting this in an official capacity, so it'll remain here in Github for anyone who wants to continue to use it or extend it. I wish someone would make a better one (sure, use this as a basis) and put it on the Supermarket so that everyone can benefit. The problem is always support and getting volunteers to do the work. There are far too many recipes on Supermarket that just aren't supported, to the point where it's easier to just roll your own (like I have with this recipe).

**Comment by davidpellerin** [comment]
@leonardteo thanks Leonard. I agree.
